version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - migration
      - database1
    expose:
      - 8000

  frontend:
    image: node:latest
    command: sh entrypoint.sh
    working_dir: /knowis_web
    volumes:
      - ./knowis_web/:/knowis_web
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./knowis_web/build:/var/www/knowis_web
    depends_on:
      - djangoapp
    ports:
      - 0.0.0.0:80:80
    networks:
      - nginx_network

  database1:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - database1_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database1
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - database1_network

  migration:
    build: .
    command: ./manage.py migrate
    volumes:
      - .:/opt/services/djangoapp
    depends_on:
      - database1
    networks:
      - database1_network

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  postgres-data:
