version: '3'
services:
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp
    ports:
      - 8000:8000
    networks:
      - database1_network
  database1:
    image: postgres
    hostname: database1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - database1_network

networks:
  database1_network:  # <-- add the bridge
    driver: bridge

volumes:
  postgres-data:
