# Generated by Django 2.0.13 on 2019-03-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': '"question_tags"',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'question')},
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together={('tag', 'question')},
        ),
    ]
