# Generated by Django 2.0.13 on 2019-05-10 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionComment',
            new_name='QuestionAnswer',
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('upvotes', 'date'), 'verbose_name': 'Question Answer', 'verbose_name_plural': 'Question Answers'},
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='comment',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='userupvote',
            old_name='comment',
            new_name='answer',
        ),
    ]
