# Generated by Django 2.0.13 on 2019-04-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190403_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='replied_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='questions.QuestionComment'),
        ),
    ]
