# Generated by Django 2.0.13 on 2019-03-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_questioncomment_downvotes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='"question_questions"',
        ),
        migrations.AlterModelTable(
            name='questioncomment',
            table='"question_answers"',
        ),
        migrations.AlterModelTable(
            name='userupvote',
            table='"question_upvotes"',
        ),
    ]
