# Generated by Django 2.0.13 on 2019-03-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190327_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='replied_to',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionComment'),
        ),
    ]
