# Generated by Django 2.0.13 on 2019-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190510_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='replied_to',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
