# Generated by Django 2.0.13 on 2019-03-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190315_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
