# Generated by Django 2.0.13 on 2019-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190403_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
