# Generated by Django 2.0.13 on 2019-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190521_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
    ]
