# Generated by Django 2.0.13 on 2019-03-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questioncomment_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='replied_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionComment'),
        ),
    ]
