# Generated by Django 2.0.13 on 2019-05-24 11:38

from django.db import migrations, models
import knowis.questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190523_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, validators=[knowis.questions.models.validate_not_blank]),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(max_length=5000, validators=[knowis.questions.models.validate_not_blank]),
        ),
    ]
