# Generated by Django 2.0.13 on 2019-03-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20190315_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='update_user',
        ),
    ]
