# Generated by Django 2.0.13 on 2019-03-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
