# Generated by Django 2.0.13 on 2019-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='avatars'),
        ),
    ]
