# Generated by Django 2.0.13 on 2019-04-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Useraccount', 'verbose_name_plural': 'Useraccounts'},
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='"useraccount_seraccount"',
        ),
    ]
