# Generated by Django 2.0.13 on 2019-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20190510_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
