# Generated by Django 2.0.13 on 2019-04-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20190409_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='"useraccount_useraccount"',
        ),
    ]
