# Generated by Django 2.0.13 on 2019-04-09 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20190409_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
