# Generated by Django 2.0.13 on 2019-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_remove_useraccount_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
